/*********************************************************************************************
** A Macro to read the MuonLifeTime.root file generated by ** Test_MuonLifeTime.cpp **
** and subtract the constant tail portion, to get the desired  decay time of 2.2 micro second
**********************************************************************************************/
// void subtrackBack(double offset)
{
  TFile *fp = new TFile("MuonLifeTime.root", "r");

  TH1F *hist = (TH1F *)fp->Get("MuonLifeTime");

  unsigned int numOfBins = hist->GetNbinsX();

  TH1F *histNew = new TH1F("histNew", "histNew", 150, 0., 15.);

  for (unsigned int i = 1; i < numOfBins - 1; i++) {
    // histNew->SetBinContent(i,hist->GetBinContent(i)-offset);
    histNew->SetBinContent(i, hist->GetBinContent(i) - 70);
  }

  histNew->Draw();
}
